name: Testing pipeline

on:
  push:
    branches: [ master ]

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' 

    - name: Test workflow  
    - run: python tests/workflow_test.py
     
     
     
     
     
     
     
     
